version: "3.7"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: silicon
      POSTGRES_USER: silicon
      POSTGRES_PASSWORD: not-for-production
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
