version: "3.7"
services:
  silicon:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - minio
      - postgres
    expose:
      - 8000
    volumes:
      - ./:/silicon/:ro

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: silicon
      POSTGRES_USER: silicon
      POSTGRES_PASSWORD: not-for-production
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  minio:
    image: minio/minio:RELEASE.2022-10-05T14-58-27Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: silicon
      MINIO_ROOT_PASSWORD: not-for-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data/:/data/
