version: "3.7"
services:
  silicon:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - minio
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://silicon:not-for-production@postgres:5432/silicon
      DEBUG: "true"
      MEILI_URL: http://meilisearch:7700
      S3_URL: minio:9000
      S3_ACCESS_KEY: K6DoFzJSfGiXaPOg
      S3_SECRET_KEY: 4gdoVkKySwoa8yX5n0qufvfnv2eQFPcP
    ports:
      - 8000:8000
    volumes:
      - ./:/silicon/:ro

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: silicon
      POSTGRES_USER: silicon
      POSTGRES_PASSWORD: not-for-production
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  meilisearch:
    image: getmeili/meilisearch:v0.29
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: "true"
    ports:
      - 7700:7700
    volumes:
      - ./meili_data/:/data.ms/

  minio:
    image: minio/minio:RELEASE.2022-10-05T14-58-27Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: K6DoFzJSfGiXaPOg
      MINIO_SECRET_KEY: 4gdoVkKySwoa8yX5n0qufvfnv2eQFPcP
      MINIO_ROOT_USER: silicon
      MINIO_ROOT_PASSWORD: not-for-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio_data/:/data/
