"""add_unique_constraint_name_brand_number_cas

Revision ID: 1886ea9538ad
Revises: 83d30f3d9b2b
Create Date: 2022-11-15 01:37:10.384699

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '1886ea9538ad'
down_revision = '83d30f3d9b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None,
        'safety_data_sheets',
        ['product_name', 'product_number', 'product_brand', 'cas_number']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'safety_data_sheets', type_='unique')
    # ### end Alembic commands ###
