"""add_product_brand_to_sds

Revision ID: 83d30f3d9b2b
Revises: 20b76d603b1f
Create Date: 2022-11-08 01:41:08.041150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d30f3d9b2b'
down_revision = '20b76d603b1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safety_data_sheets', sa.Column('product_brand', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safety_data_sheets', 'product_brand')
    # ### end Alembic commands ###
