"""add_sds_signal_word_column

Revision ID: bb8e2be0af5b
Revises: ffd5836bb31c
Create Date: 2023-02-25 02:04:37.919659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8e2be0af5b'
down_revision = 'ffd5836bb31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('safety_data_sheets', sa.Column('signal_word', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safety_data_sheets', 'signal_word')
    # ### end Alembic commands ###
