"""add_sds_hazards_column

Revision ID: ffd5836bb31c
Revises: 1886ea9538ad
Create Date: 2023-02-19 22:16:23.622162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd5836bb31c'
down_revision = '1886ea9538ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'safety_data_sheets',
        sa.Column(
            'hazards', sa.ARRAY(sa.String()),
            server_default='{}',
            nullable=False
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('safety_data_sheets', 'hazards')
    # ### end Alembic commands ###
